//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial1.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Proyecto4 : DbContext
    {
        public Proyecto4()
            : base("name=Proyecto4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MASCOTA> MASCOTA { get; set; }
        public virtual DbSet<PERSONA> PERSONA { get; set; }
    
        public virtual ObjectResult<string> ACTUALIZAR_MASCOTA(Nullable<long> iD, string nOM, Nullable<int> nDUE)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            var nOMParameter = nOM != null ?
                new ObjectParameter("NOM", nOM) :
                new ObjectParameter("NOM", typeof(string));
    
            var nDUEParameter = nDUE.HasValue ?
                new ObjectParameter("NDUE", nDUE) :
                new ObjectParameter("NDUE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ACTUALIZAR_MASCOTA", iDParameter, nOMParameter, nDUEParameter);
        }
    
        public virtual ObjectResult<string> ACTUALIZAR_PERSONA(Nullable<int> dNI, string nOM, string aPE, string gEN, string cIU, string dIR, Nullable<System.DateTime> fECH)
        {
            var dNIParameter = dNI.HasValue ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(int));
    
            var nOMParameter = nOM != null ?
                new ObjectParameter("NOM", nOM) :
                new ObjectParameter("NOM", typeof(string));
    
            var aPEParameter = aPE != null ?
                new ObjectParameter("APE", aPE) :
                new ObjectParameter("APE", typeof(string));
    
            var gENParameter = gEN != null ?
                new ObjectParameter("GEN", gEN) :
                new ObjectParameter("GEN", typeof(string));
    
            var cIUParameter = cIU != null ?
                new ObjectParameter("CIU", cIU) :
                new ObjectParameter("CIU", typeof(string));
    
            var dIRParameter = dIR != null ?
                new ObjectParameter("DIR", dIR) :
                new ObjectParameter("DIR", typeof(string));
    
            var fECHParameter = fECH.HasValue ?
                new ObjectParameter("FECH", fECH) :
                new ObjectParameter("FECH", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ACTUALIZAR_PERSONA", dNIParameter, nOMParameter, aPEParameter, gENParameter, cIUParameter, dIRParameter, fECHParameter);
        }
    
        public virtual ObjectResult<CONSULTAR_MASCOTA_Result> CONSULTAR_MASCOTA(Nullable<long> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTAR_MASCOTA_Result>("CONSULTAR_MASCOTA", iDParameter);
        }
    
        public virtual ObjectResult<CONSULTAR_MASCOTAS_Result> CONSULTAR_MASCOTAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTAR_MASCOTAS_Result>("CONSULTAR_MASCOTAS");
        }
    
        public virtual ObjectResult<CONSULTAR_MASCOTASPERSONA_Result> CONSULTAR_MASCOTASPERSONA(Nullable<int> dNI)
        {
            var dNIParameter = dNI.HasValue ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTAR_MASCOTASPERSONA_Result>("CONSULTAR_MASCOTASPERSONA", dNIParameter);
        }
    
        public virtual ObjectResult<CONSULTAR_PERSONA_Result> CONSULTAR_PERSONA(Nullable<int> dNI)
        {
            var dNIParameter = dNI.HasValue ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTAR_PERSONA_Result>("CONSULTAR_PERSONA", dNIParameter);
        }
    
        public virtual ObjectResult<CONSULTAR_PERSONAS_Result> CONSULTAR_PERSONAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CONSULTAR_PERSONAS_Result>("CONSULTAR_PERSONAS");
        }
    
        public virtual ObjectResult<string> ELIMINAR_MASCOTA(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ELIMINAR_MASCOTA", iDParameter);
        }
    
        public virtual ObjectResult<string> ELIMINAR_PERSONA(Nullable<int> dNI)
        {
            var dNIParameter = dNI.HasValue ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ELIMINAR_PERSONA", dNIParameter);
        }
    
        public virtual ObjectResult<string> INSERTAR_MASCOTA(string nOM, string tIPO, Nullable<int> dNID)
        {
            var nOMParameter = nOM != null ?
                new ObjectParameter("NOM", nOM) :
                new ObjectParameter("NOM", typeof(string));
    
            var tIPOParameter = tIPO != null ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(string));
    
            var dNIDParameter = dNID.HasValue ?
                new ObjectParameter("DNID", dNID) :
                new ObjectParameter("DNID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("INSERTAR_MASCOTA", nOMParameter, tIPOParameter, dNIDParameter);
        }
    
        public virtual ObjectResult<string> INSERTAR_PERSONA(Nullable<int> dNI, string nOM, string aPE, string gEN, string cIU, string dIR, byte[] fOT, Nullable<System.DateTime> fECH)
        {
            var dNIParameter = dNI.HasValue ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(int));
    
            var nOMParameter = nOM != null ?
                new ObjectParameter("NOM", nOM) :
                new ObjectParameter("NOM", typeof(string));
    
            var aPEParameter = aPE != null ?
                new ObjectParameter("APE", aPE) :
                new ObjectParameter("APE", typeof(string));
    
            var gENParameter = gEN != null ?
                new ObjectParameter("GEN", gEN) :
                new ObjectParameter("GEN", typeof(string));
    
            var cIUParameter = cIU != null ?
                new ObjectParameter("CIU", cIU) :
                new ObjectParameter("CIU", typeof(string));
    
            var dIRParameter = dIR != null ?
                new ObjectParameter("DIR", dIR) :
                new ObjectParameter("DIR", typeof(string));
    
            var fOTParameter = fOT != null ?
                new ObjectParameter("FOT", fOT) :
                new ObjectParameter("FOT", typeof(byte[]));
    
            var fECHParameter = fECH.HasValue ?
                new ObjectParameter("FECH", fECH) :
                new ObjectParameter("FECH", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("INSERTAR_PERSONA", dNIParameter, nOMParameter, aPEParameter, gENParameter, cIUParameter, dIRParameter, fOTParameter, fECHParameter);
        }
    }
}
